name: Mutmut Mutation Test

on: 
  workflow_dispatch:

jobs:
  mutmut:
    name: Mutation Test with Mutmut
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          pip install mutmut --upgrade
      - name: Mutmut Run
        run: python3 -m mutmut run --no-progress --rerun-all --paths-to-mutate src
      - name: Mutmut Results
        if: ${{ always() }}
        run: python3 -m mutmut results
      - name: Mutmut Report
        if: ${{ always() }}
        run: |
          python3 -m mutmut html
          python3 -m mutmut junitxml > mutation-testing-report.xml
          head mutation-testing-report.xml -n 3
      - name: Upload Report HTML
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Mutation testing report HTML
          path: html
      - name: Upload Report XML
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Mutation testing report XML
          path: mutation-testing-report.xml
