name: Poodle Mutation Test

on: 
  workflow_dispatch:

jobs:
  poodle:
    name: Mutation Test with Poodle
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          pip install --editable .
      - name: poodle
        run: |
          pytest --cov=src --cov-context=test
          poodle --report json
      - name: Upload Report HTML
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Mutation testing report HTML
          path: mutation_reports
      - name: save-json-report
        if: ${{ github.ref_name == 'main' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: "mutation-testing-report.json"
          pull: "--rebase=true --autostash"