name: Python Mutation Test

on: 
  workflow_dispatch:

jobs:
  mutmut:
    name: Mutation Test with Mutmut
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          pip install mutmut --upgrade
          pip install --editable .
      - name: Mutmut
        run: python3 -m mutmut run --no-progress --rerun-all --paths-to-mutate src --runner "pytest --exitfirst --assert=plain --sort-mode=diffcov" || true
      - run: python3 -m mutmut results
        if: ${{ always() }}
      - name: Mutmut Report
        if: ${{ always() }}
        run: |
          python3 -m mutmut html
          python3 -m mutmut junitxml > mutation-testing-report.xml
          head mutation-testing-report.xml -n 3
      - name: save-reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Mutation testing report
          path: html
